jobs:
  include:
  - stage: Build binaries
    os: linux
    env: WINDOWS=1
    language: java
    jdk: openjdk8
    workspaces:
      create:
        name: windows-binaries
        paths: /tmp/output/windows
    script: .travis/build.windows.sh
  - os: linux
    language: java
    jdk: openjdk8
    services: docker
    workspaces:
      create:
        name: linux-binaries
        paths: /tmp/output/linux
    script: .travis/build.linux.sh
  - os: osx
    osx_image: xcode11.3
    language: objective_c
    workspaces:
      create:
        name: osx-binaries
        paths: /tmp/output/osx
    script: .travis/build.osx.sh
  - stage: Collect binaries
    language: minimal
    workspaces:
      use:
      - windows-binaries
      - linux-binaries
      - osx-binaries
    script: .travis/collect-binaries.sh
    deploy:
      provider: releases
      api_key: "$GITHUB_UPLOAD_KEY"
      file:
        # iOS files
      - /tmp/output/windows/data
        #TotalCrossSDK/dist/vm/ios/TotalCross.ipa
      - TotalCrossVM/builders/xcode/build/Release-iphoneos/TotalCross.xcarchive
        # Linux files
      - TotalCrossVM/builders/gcc-posix/launcher/bin/Launcher
      - TotalCrossVM/builders/gcc-posix/tcvm/bin/libtcvm.so
      draft: true
      on:
        branch: travis

addons:
  apt:
    packages:
    - ant
    - ninja-build
    - sshpass
  homebrew:
    packages:
    - cocoapods
    taps: homebrew/cask-versions
    casks: adoptopenjdk8

env:
  global:
    - WORKSPACE=$TRAVIS_BUILD_DIR
    - ANDROID_HOME=$HOME/android-sdk
    - ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
    - ANDROID_NDK_HOME=$ANDROID_NDK_ROOT

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

