jobs:
  include:
  - stage: Build binaries
    os: linux
    env: WINDOWS=1
    language: java
    jdk: openjdk8
    workspaces:
      create:
        name: windows-binaries
        paths: /tmp/output/windows
    script: .travis/build.windows.sh
  - os: linux
    language: java
    jdk: openjdk8
    services: docker
    workspaces:
      create:
        name: linux-binaries
        paths: /tmp/output/linux
    script: .travis/build.linux.sh
  - os: osx
    osx_image: xcode11.3
    language: objective_c
    workspaces:
      create:
        name: osx-binaries
        paths: /tmp/output/osx
    script: .travis/build.osx.sh
  - stage: Collect binaries
    language: minimal
    workspaces:
      use:
      - windows-binaries
      - linux-binaries
      - osx-binaries
    script: .travis/collect-binaries.sh
    deploy:
      provider: releases
      api_key: "$GITHUB_UPLOAD_KEY"
      file:
        # iOS files
      - /tmp/output/windows/data
        #TotalCrossSDK/dist/vm/ios/TotalCross.ipa
      - TotalCrossVM/builders/xcode/build/Release-iphoneos/TotalCross.xcarchive
        # Linux files
      - TotalCrossVM/builders/gcc-posix/launcher/bin/Launcher
      - TotalCrossVM/builders/gcc-posix/tcvm/bin/libtcvm.so
      draft: true
      on:
        branch: travis


